apiVersion: apps/v1
kind: Deployment
metadata:
  name: sifood-srikandi-dashboard-canary
  namespace: default
spec:
  selector:
    matchLabels:
      app: sifood-srikandi-dashboard-canary
      type: canary
  template:
    metadata:
      labels:
        app: sifood-srikandi-dashboard-canary
        type: canary
    spec:
      containers:
      - name: sifood-srikandi-dashboard-canary
        image: IMAGE
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: sifood-srikandi-dashboard

---
apiVersion: v1
kind: Service
metadata:
  name: sifood-srikandi-dashboard
  namespace: default
spec:
  selector:
    app: sifood-srikandi-dashboard
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sifood-srikandi-dashboard-destionationrule
  namespace: default
spec:
  host: sifood-srikandi-dashboard.default.svc.cluster.local
  subsets:
  - name: full # DNS-1123 label naming conventions
    labels:
      type: full
  - name: canary # DNS-1123 label naming conventions
    labels:
      type: canary

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sifood-srikandi-dashboard-virtualservice
  namespace: default
spec:
  hosts:
  - sifood-srikandi-dashboard.default.svc.cluster.local
  http:
  - name: "full route"
    route:
    - destination:
        host: sifood-srikandi-dashboard.default.svc.cluster.local
        subset: full
      weight: 80 
    - destination:
        host: sifood-srikandi-dashboard.default.svc.cluster.local
        subset: canary
      weight: 20 